In [26]:
import pandas as pd
import numpy as np

# Loading dataset

In [27]:
df = pd.read_csv(r"C:\Users\VISHAL\OneDrive\Pictures\Documents\Infotact project\ATMOSYN_my\iot_sensor_readings.xls")
df.head()

,reading_id,shipment_id,container_id,timestamp,temperature,humidity,vibration,latitude,longitude
0,READ0000001,SHP0001,CNT1001,2026-08-08 13:15:00,5.08,43.90,0.029,10.0317,76.2380
1,READ0000002,SHP0001,CNT1001,2026-08-08 13:30:00,5.17,40.51,0.153,10.1214,76.2015
2,READ0000003,SHP0001,CNT1001,2026-08-08 13:45:00,4.75,47.61,0.089,10.1998,76.1592
3,READ0000004,SHP0001,CNT1001,2026-08-08 14:00:00,4.71,47.30,0.093,10.2928,76.1340
4,READ0000005,SHP0001,CNT1001,2026-08-08 14:15:00,5.01,54.81,0.673,10.3941,76.0918

# Understanding dataset

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   reading_id    50000 non-null  object
 1   shipment_id   50000 non-null  object
 2   container_id  50000 non-null  object
 3   timestamp     50000 non-null  object
 4   temperature   50000 non-null  float64
 5   humidity      50000 non-null  float64
 6   vibration     50000 non-null  float64
 7   latitude      50000 non-null  float64
 8   longitude     50000 non-null  float64
dtypes: float64(5), object(4)
memory usage: 3.4+ MB

In [10]:
df.describe()

        temperature      humidity     vibration      latitude     longitude
count  50000.000000  50000.000000  50000.000000  50000.000000  50000.000000
mean       5.543334     52.555554      0.126371     17.603635     77.432289
std        2.284697      7.214756      0.126843      4.844972      3.415900
min        4.600000     40.000000      0.020000      8.515300     72.561900
25%        4.810000     46.310000      0.062000     13.683600     75.094550
50%        5.030000     52.590000      0.104000     17.591400     76.975400
75%        5.240000     58.820000      0.146000     21.154975     78.678725
max       21.550000     65.000000      0.850000     28.713900     88.373000

In [11]:
df.head()

,reading_id,shipment_id,container_id,timestamp,temperature,humidity,vibration,latitude,longitude
0,READ0000001,SHP0001,CNT1001,2026-08-08 13:15:00,5.08,43.90,0.029,10.0317,76.2380
1,READ0000002,SHP0001,CNT1001,2026-08-08 13:30:00,5.17,40.51,0.153,10.1214,76.2015
2,READ0000003,SHP0001,CNT1001,2026-08-08 13:45:00,4.75,47.61,0.089,10.1998,76.1592
3,READ0000004,SHP0001,CNT1001,2026-08-08 14:00:00,4.71,47.30,0.093,10.2928,76.1340
4,READ0000005,SHP0001,CNT1001,2026-08-08 14:15:00,5.01,54.81,0.673,10.3941,76.0918

In [12]:
df.tail()

,reading_id,shipment_id,container_id,timestamp,temperature,humidity,vibration,latitude,longitude
49995,READ0049996,SHP0500,CNT1500,2026-08-03 00:24:00,5.19,52.20,0.161,18.8234,73.0672
49996,READ0049997,SHP0500,CNT1500,2026-08-03 00:43:12,5.29,49.90,0.575,18.8895,73.0156
49997,READ0049998,SHP0500,CNT1500,2026-08-03 01:02:24,4.94,58.66,0.169,18.9451,72.9628
49998,READ0049999,SHP0500,CNT1500,2026-08-03 01:21:36,4.86,47.18,0.151,19.0241,72.9159
49999,READ0050000,SHP0500,CNT1500,2026-08-03 01:40:48,4.83,57.21,0.128,19.0746,72.8790

# Checking Missing Values

In [13]:
df.isnull().sum()     
# Checking missing values

reading_id      0
shipment_id     0
container_id    0
timestamp       0
temperature     0
humidity        0
vibration       0
latitude        0
longitude       0
dtype: int64

# Checking Duplicates

In [14]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

# 6. Unique Value Analysis

In [20]:
for column in df.columns:
    print(f"\n{column}:")
    print("Unique values:", df[column].nunique())

reading_id:
Unique values: 50000

shipment_id:
Unique values: 500

container_id:
Unique values: 500

timestamp:
Unique values: 30731

temperature:
Unique values: 1449

humidity:
Unique values: 2501

vibration:
Unique values: 609

latitude:
Unique values: 42227

longitude:
Unique values: 37952

# 7. Statistical Summary

In [21]:
df[[
    "temperature",
    "humidity",
    "vibration",
    "latitude",
    "longitude"
]].describe()

        temperature      humidity     vibration      latitude     longitude
count  50000.000000  50000.000000  50000.000000  50000.000000  50000.000000
mean       5.543334     52.555554      0.126371     17.603635     77.432289
std        2.284697      7.214756      0.126843      4.844972      3.415900
min        4.600000     40.000000      0.020000      8.515300     72.561900
25%        4.810000     46.310000      0.062000     13.683600     75.094550
50%        5.030000     52.590000      0.104000     17.591400     76.975400
75%        5.240000     58.820000      0.146000     21.154975     78.678725
max       21.550000     65.000000      0.850000     28.713900     88.373000

# 8.1 Temperature Excursion Analysis

In [22]:
high_temp = df[df["temperature"] > 8]

print("Temperature readings above 8°C:", len(high_temp))

display(high_temp.head(10))

Temperature readings above 8°C: 2894

,reading_id,shipment_id,container_id,timestamp,temperature,humidity,vibration,latitude,longitude
245,READ0000246,SHP0003,CNT1003,2026-08-19 06:45:00,8.02,60.20,0.148,9.1694,76.6253
246,READ0000247,SHP0003,CNT1003,2026-08-19 07:09:00,8.16,53.61,0.546,9.1841,76.6284
247,READ0000248,SHP0003,CNT1003,2026-08-19 07:33:00,8.44,49.71,0.058,9.1968,76.6133
248,READ0000249,SHP0003,CNT1003,2026-08-19 07:57:00,8.58,55.09,0.119,9.2110,76.6032
249,READ0000250,SHP0003,CNT1003,2026-08-19 08:21:00,8.90,52.98,0.024,9.2269,76.5995
250,READ0000251,SHP0003,CNT1003,2026-08-19 08:45:00,9.11,54.50,0.117,9.2385,76.5929
251,READ0000252,SHP0003,CNT1003,2026-08-19 09:09:00,9.40,63.89,0.488,9.2611,76.5948
252,READ0000253,SHP0003,CNT1003,2026-08-19 09:33:00,9.72,46.09,0.030,9.2600,76.5848
253,READ0000254,SHP0003,CNT1003,2026-08-19 09:57:00,9.87,52.15,0.066,9.2926,76.5722
254,READ0000255,SHP0003,CNT1003,2026-08-19 10:21:00,10.11,47.78,0.135,9.2942,76.5745

# 8.2 High-Temperature Readings by Shipment

In [28]:
high_temp.groupby("shipment_id") \
    .size() \
    .sort_values(ascending=False) \
    .head(10)

shipment_id
SHP0390    100
SHP0003     55
SHP0225     54
SHP0177     54
SHP0083     54
SHP0092     54
SHP0304     54
SHP0368     53
SHP0294     53
SHP0289     53
dtype: int64

# 8.3 High-Temperature Readings by Container

In [24]:
high_temp.groupby("shipment_id").size().sort_values(ascending=False).head(10)

shipment_id
SHP0390    100
SHP0003     55
SHP0225     54
SHP0177     54
SHP0083     54
SHP0092     54
SHP0304     54
SHP0368     53
SHP0294     53
SHP0289     53
dtype: int64

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   reading_id    50000 non-null  object
 1   shipment_id   50000 non-null  object
 2   container_id  50000 non-null  object
 3   timestamp     50000 non-null  object
 4   temperature   50000 non-null  float64
 5   humidity      50000 non-null  float64
 6   vibration     50000 non-null  float64
 7   latitude      50000 non-null  float64
 8   longitude     50000 non-null  float64
dtypes: float64(5), object(4)
memory usage: 3.4+ MB

## Conclusion

- The Sensor Readings dataset contains **50,000 records and 9 columns** related to vaccine shipment monitoring. The initial data understanding process was performed to identify missing values, duplicate records, data distribution, and potential data-quality issues.

- The analysis found **no missing values** and **no duplicate rows**. The `reading_id` values are unique, while multiple readings are associated with the same shipment and container, which is expected for sensor data.

- The sensor values were also examined. Humidity, vibration, latitude, and longitude showed reasonable ranges. However, **2,894 temperature readings were above 8°C**, with temperatures reaching a maximum of **21.55°C**. These records should not be removed automatically because they may represent genuine **cold-chain temperature excursions**.

- Therefore, the high-temperature readings will be **identified and flagged during the data-cleaning stage**, while preserving the original sensor values. Further validation and cleaning will be performed in the next notebook.

- **Next Step:** Proceed to `02_data_cleaning.ipynb` to clean, validate, and prepare the dataset for further analysis.